name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg VERACODE_WRAPPER_VERSION="20.8.7.1" --build-arg VERSION="1.0.1" --tag dennismedeiros/veracode-wrapperapi:latest
